### ISSUE TITLE
About our vizualisations: Add section headers in right-hand sidebar

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#15]
## Page URL: 

https://mabarber92.github.io/data/viz

This page is missing the right-hand sidebar with the table of contents of the page

**Comment by mabarber92** [comment]
Thanks so much for all these detailed issues. Coming back to this one now, because I remember the technical reason for why the TOC isn't there.

The issue is as follows:

I have used an 'archive' type layout for the page (so we can have constantly updating blogs at the bottom of the page, ones that are tagged 'viz'). The trade off for this is that the theme will not allow you to use a sidebar TOC with this layout chosen (at least so far as I have seen).

Do you think it's better to leave the blogs off and have the TOC, or keep it as is?

**Comment by pverkind** [comment]
Hi Mathew, I think it's probably better to have the sidebar TOC; we could include "blogs about visualization" (or something similar) as an entry in the left-hand sidebar, and link to that at the bottom of the "About our Vizualisations" section?

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Content updates](https://trello.com/c/KOfyPVOv/27-content-updates)

**Comment by mabarber92** [comment]
Thank you! See updates here: https://mabarber92.github.io/data/viz

Let me know if this is all ok.
