### ISSUE TITLE
Documentation: add intermediate page

### ISSUE THREAD

**Issue by pverkind** [mabarber92/mabarber92.github.io#19]
## Page URL: 
(all pages)

Currently, the "Documentation" entry in the menu at the top of the page links directly to the OpenITI documentation (https://openiti.github.io/documentation/)

Would it not be better to have a Documentation page like we have a page for each of the other main sections, and from there, link to the OpenITI documentation? At some point, we will have documentation that is not OpenITI-related as welll.

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Nav updates](https://trello.com/c/wWWHo1cG/26-nav-updates)

**Comment by mabarber92** [comment]
This change has now been added, see here: https://mabarber92.github.io/docs/openITI

Unfortunately to get the images to work, I had to find and replace the starts of the image addresses in the documentation (I think this is due to the workings of Jekyll, but not completely sure).

I'll work on a process that automatically grabs this data from the OpenITI Docs whenever the website is updated.
